[tool.poetry]
name = "ml_api_builder"
version = "0.1.44"
description = ""
authors = ["Michael Henzl <michael.henzl@seznam.cz>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.20.1"
pandas = "^1.2.1"
python-jenkins = "^1.7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
