[tool.poetry]
name = "costack_sdk"
version = "0.1.5"
description = "the sdk to support lambda workflows and seamless integrations"
authors = ["perseus.yang <perseus.yang@getcostack.com>"]

[tool.poetry.dependencies]
python = "^3.7"
config = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
