[tool.poetry]
name = "lgg"
version = "0.1.0"
description = "A simple yet fancy logger for Python scripts"
authors = ["Ayoub Assis <assis.ayoub@gmail.com>"]
license = "MIT License"
readme = "README.md"

homepage = "https://github.com/blurry-mood/python-logger"
repository = "https://github.com/blurry-mood/python-logger"

packages = [
    { include = "src" }
]
include = [
    "LICENSE"
]
keywords = [
    "Python", "Logger", "Fancy Logger"
]

[tool.poetry.dependencies]
python = "^3.7"
flake9 = "^3.8.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
