[tool.poetry]
name = "mapaction"
version = "0.1.9"
description = "CLI for managing some MapAction tasks"
readme = "README.md"
documentation = "https://github.com/mapaction/mapaction-cli/wiki/About"
repository = "https://github.com/mapaction/mapaction-cli"
authors = ["Hugh Loughrey <hloughrey@mapaction.org>"]

[tool.poetry.dependencies]
python = "^3.7"
typer = "^0.4.0"
colorama = "^0.4.4"
shellingham = "^1.4.0"
requests = "^2.27.1"
packaging = "^21.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.17.0"
mypy = "^0.931"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mapaction = "mapaction.cli:run"
