[tool.poetry]
name = "nautobot_utsc"
version = "2022.4.25"
description = "A collection of UTSC-specific modifications and extensions to Nautobot."
authors = ["Alex Tremblay <alex.tremblay@utoronto.ca>", "University of Toronto Governing Council <governing.council@utoronto.ca>"]
license = "MIT"
packages = [
  { include = "nautobot_utsc", from = "src" }
]


# [tool.poetry.scripts]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
nautobot_ssot = ">=1.1.0"
"utsc.core" = "*"
nautobot = ">=1.3"
django-auth-ldap = "*" 
debugpy = "*"
django-debug-toolbar = "*"
html-table-parser-python3 = ">=0.2.0"


[tool.poe.tasks]
cov.cmd = "pytest --cov-report xml:cov.xml --cov-report term-missing --cov"
publish.shell = """\
  git push
  poetry build
  poetry publish
  """
check.shell = """\
  black .
  mypy .
  prospector .
  pytest .
  """

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
